<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>test login - order</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ad3c1980-ee44-4060-b0fd-a1bf453a1d98</testSuiteGuid>
   <testCaseLink>
      <guid>9547abf0-9659-4799-80b0-eda408b1c305</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login - Logout</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a20129e-f2cb-4767-9ff8-0e97cb0d2eeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2043d293-19ef-4746-ac78-446a3f7169cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17b268d1-28fb-4ef9-b636-a643d1471a64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/order-menu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>863644fd-218c-4580-aca3-ba31b1a9cc6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb19622c-82ef-428d-84b3-c3b30d09a44b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e62258e8-4b2f-4fde-8324-939fa40daafb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21a8e0c0-962c-49c8-87a6-2eb7a7e001d8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
