<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-nasi</name>
   <tag></tag>
   <elementGuidId>08636766-5ffc-42a1-ae7a-f63fa63e166f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;modal-default&quot;]//div[@class=&quot;modal-body&quot;]//button[contains(text(),'Nasi')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
